# News Category Classification

In [51]:
from importlib import reload
import sys
from imp import reload
import warnings
warnings.filterwarnings('ignore')
if sys.version[0] == '2':
    reload(sys)
    sys.setdefaultencoding("utf-8")

In [52]:
import pandas as pd

df = pd.read_json('datasets/news.json', lines=True)
df.head()

category                                           headline  \
0          CRIME  There Were 2 Mass Shootings In Texas Last Week...   
1  ENTERTAINMENT  Will Smith Joins Diplo And Nicky Jam For The 2...   
2  ENTERTAINMENT    Hugh Grant Marries For The First Time At Age 57   
3  ENTERTAINMENT  Jim Carrey Blasts 'Castrato' Adam Schiff And D...   
4  ENTERTAINMENT  Julianna Margulies Uses Donald Trump Poop Bags...   

           authors                                               link  \
0  Melissa Jeltsen  https://www.huffingtonpost.com/entry/texas-ama...   
1    Andy McDonald  https://www.huffingtonpost.com/entry/will-smit...   
2       Ron Dicker  https://www.huffingtonpost.com/entry/hugh-gran...   
3       Ron Dicker  https://www.huffingtonpost.com/entry/jim-carre...   
4       Ron Dicker  https://www.huffingtonpost.com/entry/julianna-...   

                                   short_description       date  
0  She left her husband. He killed their children... 2018-05-26  
1                           Of course it has a song. 2018-05-26  
2  The actor and his longtime girlfriend Anna Ebe... 2018-05-26  
3  The actor gives Dems an ass-kicking for not fi... 2018-05-26  
4  The "Dietland" actress said using the bags is ... 2018-05-26

In [53]:
df = df.drop(['authors', 'link', 'date'], axis=1)
df.head()

category                                           headline  \
0          CRIME  There Were 2 Mass Shootings In Texas Last Week...   
1  ENTERTAINMENT  Will Smith Joins Diplo And Nicky Jam For The 2...   
2  ENTERTAINMENT    Hugh Grant Marries For The First Time At Age 57   
3  ENTERTAINMENT  Jim Carrey Blasts 'Castrato' Adam Schiff And D...   
4  ENTERTAINMENT  Julianna Margulies Uses Donald Trump Poop Bags...   

                                   short_description  
0  She left her husband. He killed their children...  
1                           Of course it has a song.  
2  The actor and his longtime girlfriend Anna Ebe...  
3  The actor gives Dems an ass-kicking for not fi...  
4  The "Dietland" actress said using the bags is ...

In [54]:
df['information'] = df[['headline', 'short_description']].apply(lambda x: ' '.join(x), axis=1)
df.head()

category                                           headline  \
0          CRIME  There Were 2 Mass Shootings In Texas Last Week...   
1  ENTERTAINMENT  Will Smith Joins Diplo And Nicky Jam For The 2...   
2  ENTERTAINMENT    Hugh Grant Marries For The First Time At Age 57   
3  ENTERTAINMENT  Jim Carrey Blasts 'Castrato' Adam Schiff And D...   
4  ENTERTAINMENT  Julianna Margulies Uses Donald Trump Poop Bags...   

                                   short_description  \
0  She left her husband. He killed their children...   
1                           Of course it has a song.   
2  The actor and his longtime girlfriend Anna Ebe...   
3  The actor gives Dems an ass-kicking for not fi...   
4  The "Dietland" actress said using the bags is ...   

                                         information  
0  There Were 2 Mass Shootings In Texas Last Week...  
1  Will Smith Joins Diplo And Nicky Jam For The 2...  
2  Hugh Grant Marries For The First Time At Age 5...  
3  Jim Carrey Blasts 'Castrato' Adam Schiff And D...  
4  Julianna Margulies Uses Donald Trump Poop Bags...

In [55]:
news = df
news.to_csv(r'datasets/news.csv', index=False)

In [56]:
news.head()

category                                           headline  \
0          CRIME  There Were 2 Mass Shootings In Texas Last Week...   
1  ENTERTAINMENT  Will Smith Joins Diplo And Nicky Jam For The 2...   
2  ENTERTAINMENT    Hugh Grant Marries For The First Time At Age 57   
3  ENTERTAINMENT  Jim Carrey Blasts 'Castrato' Adam Schiff And D...   
4  ENTERTAINMENT  Julianna Margulies Uses Donald Trump Poop Bags...   

                                   short_description  \
0  She left her husband. He killed their children...   
1                           Of course it has a song.   
2  The actor and his longtime girlfriend Anna Ebe...   
3  The actor gives Dems an ass-kicking for not fi...   
4  The "Dietland" actress said using the bags is ...   

                                         information  
0  There Were 2 Mass Shootings In Texas Last Week...  
1  Will Smith Joins Diplo And Nicky Jam For The 2...  
2  Hugh Grant Marries For The First Time At Age 5...  
3  Jim Carrey Blasts 'Castrato' Adam Schiff And D...  
4  Julianna Margulies Uses Donald Trump Poop Bags...

In [57]:
df = df.drop(['headline', 'short_description'], axis=1)
df.head()

category                                        information
0          CRIME  There Were 2 Mass Shootings In Texas Last Week...
1  ENTERTAINMENT  Will Smith Joins Diplo And Nicky Jam For The 2...
2  ENTERTAINMENT  Hugh Grant Marries For The First Time At Age 5...
3  ENTERTAINMENT  Jim Carrey Blasts 'Castrato' Adam Schiff And D...
4  ENTERTAINMENT  Julianna Margulies Uses Donald Trump Poop Bags...

In [58]:
categories = df.groupby('category').size().sort_values(ascending=False)
categories

category
POLITICS          32739
WELLNESS          17827
ENTERTAINMENT     16058
TRAVEL             9887
STYLE & BEAUTY     9649
PARENTING          8677
HEALTHY LIVING     6694
QUEER VOICES       6314
FOOD & DRINK       6226
BUSINESS           5937
COMEDY             5175
SPORTS             4884
BLACK VOICES       4528
HOME & LIVING      4195
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3651
WOMEN              3490
IMPACT             3459
DIVORCE            3426
CRIME              3405
MEDIA              2815
WEIRD NEWS         2670
GREEN              2622
WORLDPOST          2579
RELIGION           2556
STYLE              2254
SCIENCE            2178
WORLD NEWS         2177
TASTE              2096
TECH               2082
MONEY              1707
ARTS               1509
FIFTY              1401
GOOD NEWS          1398
ARTS & CULTURE     1339
ENVIRONMENT        1323
COLLEGE            1144
LATINO VOICES      1129
CULTURE & ARTS     1030
EDUCATION          1004
dtype: 

In [59]:
from sklearn.model_selection import train_test_split

TOP_N_CATEGORIES = 15

df = df[df.category.apply(lambda x: x in categories.index[:TOP_N_CATEGORIES]) &\
            (df.information.apply(len) > 0)]
df_train, df_test = train_test_split(df, test_size=.1, random_state=31)

In [60]:
df_train.head()

category                                        information
126261         TRAVEL  10 Reasons You Should ALWAYS Ask For The Windo...
105073  ENTERTAINMENT  Nicki Minaj's New Song Reveals She Almost Had ...
22595        POLITICS  GOP Donor Who Reportedly Sought Clinton Emails...
78861   ENTERTAINMENT  Aaron Sorkin Slams Sony Hack As 'Terrorism' Th...
50575    BLACK VOICES  Bishop Eddie Long On Weight Loss: I Stopped Ea...

In [61]:
MAX_SEQUENCE_LEN = 25
UNK = 'UNK'
PAD = 'PAD'

def text_to_id_list(text, dictionary):
    return [dictionary.token2id.get(tok, dictionary.token2id.get(UNK))
            for tok in text_to_tokens(text)]

def texts_to_input(texts, dictionary):
    return sequence.pad_sequences(
        list(map(lambda x: text_to_id_list(x, dictionary), texts)), maxlen=MAX_SEQUENCE_LEN,
        padding='post', truncating='post', value=dictionary.token2id.get(PAD))

def text_to_tokens(text):
    return [tok.text.lower() for tok in nlp.tokenizer(text)
            if not (tok.is_punct or tok.is_quote)]

def build_dictionary(texts):
    d = Dictionary(text_to_tokens(t)for t in texts)
    d.filter_extremes(no_below=3, no_above=1)
    d.add_documents([[UNK, PAD]])
    d.compactify()
    return d

In [62]:
from gensim.corpora import Dictionary
import spacy
nlp = spacy.load('en')

dictionary = build_dictionary(df.information)

In [63]:
from tensorflow.keras.preprocessing import sequence

x_train = texts_to_input(df_train.information, dictionary)
x_test = texts_to_input(df_test.information, dictionary)

In [64]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
lb.fit(categories.index[:TOP_N_CATEGORIES])
y_train = lb.transform(df_train.category)
y_test = lb.transform(df_test.category)

In [68]:
from tensorflow.keras.models import Model
import tensorflow.keras.layers as layers

EMBEDDING_DIM = 50

inp = layers.Input(shape=(MAX_SEQUENCE_LEN,), dtype='float32')
emb = layers.Embedding(len(dictionary), EMBEDDING_DIM, input_length=MAX_SEQUENCE_LEN)(inp)
filters = []
for kernel_size in [2, 3, 4]:
    conv = layers.Conv1D(32, kernel_size, padding='same', activation='relu', strides=1)(emb)
    pooled = layers.MaxPooling1D(pool_size=MAX_SEQUENCE_LEN-kernel_size+1)(conv)
    filters.append(pooled)

stacked = layers.Concatenate()(filters)
flatten = layers.Flatten()(stacked)
drop = layers.Dropout(0.2)(flatten)
out = layers.Dense(15, activation='softmax')(drop)

model = Model(inputs=inp, outputs=out)
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [69]:
model.summary()

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 25)]         0                                            
__________________________________________________________________________________________________
embedding_2 (Embedding)         (None, 25, 50)       1769500     input_3[0][0]                    
__________________________________________________________________________________________________
conv1d_6 (Conv1D)               (None, 25, 32)       3232        embedding_2[0][0]                
__________________________________________________________________________________________________
conv1d_7 (Conv1D)               (None, 25, 32)       4832        embedding_2[0][0]                
____________________________________________________________________________________________

In [70]:
model.fit(x_train, y_train, epochs=5, batch_size=128, validation_data=(x_test, y_test))

Train on 128470 samples, validate on 14275 samples
Epoch 1/5
128470/128470 [==============================] - ETA: 19:27 - loss: 2.6970 - accuracy: 0.101 - ETA: 6:55 - loss: 2.6905 - accuracy: 0.072 - ETA: 4:26 - loss: 2.6868 - accuracy: 0.10 - ETA: 3:21 - loss: 2.6773 - accuracy: 0.13 - ETA: 2:45 - loss: 2.6707 - accuracy: 0.15 - ETA: 2:21 - loss: 2.6615 - accuracy: 0.16 - ETA: 2:05 - loss: 2.6534 - accuracy: 0.17 - ETA: 1:53 - loss: 2.6475 - accuracy: 0.18 - ETA: 1:45 - loss: 2.6380 - accuracy: 0.19 - ETA: 1:38 - loss: 2.6304 - accuracy: 0.20 - ETA: 1:32 - loss: 2.6258 - accuracy: 0.20 - ETA: 1:27 - loss: 2.6156 - accuracy: 0.20 - ETA: 1:23 - loss: 2.6082 - accuracy: 0.21 - ETA: 1:19 - loss: 2.6031 - accuracy: 0.21 - ETA: 1:16 - loss: 2.5987 - accuracy: 0.21 - ETA: 1:13 - loss: 2.5933 - accuracy: 0.21 - ETA: 1:11 - loss: 2.5866 - accuracy: 0.21 - ETA: 1:09 - loss: 2.5790 - accuracy: 0.21 - ETA: 1:07 - loss: 2.5709 - accuracy: 0.21 - ETA: 1:05 - loss: 2.5647 - accuracy: 0.22 - ETA: 1:

In [71]:
import numpy as np
from sklearn.metrics import classification_report

y_test_pred = [lb.classes_[i] for i in np.argmax(model.predict(x_test), axis=1)]
print(classification_report(df_test.category, y_test_pred))

                precision    recall  f1-score   support

  BLACK VOICES       0.61      0.51      0.56       447
      BUSINESS       0.66      0.57      0.61       631
        COMEDY       0.58      0.45      0.50       492
 ENTERTAINMENT       0.73      0.79      0.76      1543
  FOOD & DRINK       0.78      0.78      0.78       595
HEALTHY LIVING       0.55      0.39      0.46       706
 HOME & LIVING       0.75      0.75      0.75       412
     PARENTING       0.63      0.68      0.65       872
       PARENTS       0.53      0.33      0.41       368
      POLITICS       0.84      0.90      0.87      3254
  QUEER VOICES       0.81      0.70      0.75       661
        SPORTS       0.77      0.72      0.75       489
STYLE & BEAUTY       0.86      0.83      0.85       984
        TRAVEL       0.82      0.79      0.81      1034
      WELLNESS       0.67      0.81      0.73      1787

      accuracy                           0.74     14275
     macro avg       0.71      0.67      0.68 

In [72]:
x_train[23:24]

array([[ 9632, 35389,  2300,   765,   272,   761,   187,     2,  2398,
         1274,   802,   254,   212,  1959,   118,   187,   680,    73,
          581, 35388, 35388, 35388, 35388, 35388, 35388]])

In [73]:
y_train[23:24]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [74]:
result = model.predict(x_train[23:24])
result

array([[9.0026508e-05, 2.1147866e-04, 2.5734806e-04, 1.0179051e-03,
        1.3625133e-06, 1.5920102e-04, 3.6197369e-05, 4.1559165e-06,
        2.3381783e-04, 3.7660680e-03, 9.9408984e-01, 6.1620689e-05,
        6.9843595e-06, 6.1823288e-05, 2.2011577e-06]], dtype=float32)

In [76]:
df_train[23:24]

category                                        information
26777  QUEER VOICES  Barry Manilow: Coming Out As Gay Was A 'Beauti...

In [78]:
model.save('models/news/news_model.h5')